### ISSUE TITLE
Upgrade from `8.5.24` to `9.0.1` breaks Mmenu on all sites for me.

### ISSUE THREAD

**Issue by sjclark** [FrDH/mmenu-js#1264] opened 2021-12-15 08:04 UTC
All Menus will not close when clicking on the dimmed portion of the screen.
```
import 'mmenu-js';
document.addEventListener(
  "DOMContentLoaded", () => {
    const menu = new Mmenu("#mobile-menu", {
      extensions: ["position-right", "pagedim-black", "shadow-page", "theme-light", "position-front"],
    });
    const api = menu.API;

    document.querySelector("#mburger")
      .addEventListener(
        "click", (evnt) => {
          evnt.preventDefault();
          api.open();
        }
      );
  }
);
```

The `mm-wrapper__blocker` element changes from a `div` to an `a` in the new version, and doesn't respond to any clicks. Nothing is logged. Escape key still exits. 

Is there any further info I can provide?

Rolling back to `8.5.24` sorts things.

**Comment by andreanironi** [comment] 2021-12-16 09:40
Same as https://github.com/FrDH/mmenu-js/issues/1261 , can confirm the issue

**Comment by sjclark** [comment] 2021-12-16 11:52
As confirmed in https://github.com/FrDH/mmenu-js/issues/1261#issuecomment-986957836 the Mmenu site itself even seems to have this issue for me.

**Comment by MikeyJN** [comment] 2021-12-16 16:51
> As confirmed in [#1261 (comment)](https://github.com/FrDH/mmenu-js/issues/1261#issuecomment-986957836) the Mmenu site itself even seems to have this issue for me.

Even on devices where the website appears OK (my 15.4" laptop for example), zooming out even 10% within the browser causes the behaviour.

One other issue I've found which may be related, is that on the following example when the page loads it displays part of the menu open before quickly closing again: https://mmenujs.com/demo/index.html?demo=menu-advanced-2

**Comment by jannakha** [comment] 2022-01-26 15:15
so the issue is in the switch statement in a listener:

https://github.com/FrDH/mmenu-js/blob/92fafdd60baf04c4507d121b5cc26b158e13e938/dist/core/offcanvas/mmenu.offcanvas.js#L78

it's never true because:
- href value on https://github.com/FrDH/mmenu-js/blob/92fafdd60baf04c4507d121b5cc26b158e13e938/dist/core/offcanvas/mmenu.offcanvas.js#L70
- is being stripped of `mm-` in https://github.com/FrDH/mmenu-js/blob/92fafdd60baf04c4507d121b5cc26b158e13e938/dist/_modules/helpers.js#L92


so if your menu id is `mm-3` and close menu container will have `href='mm-3'` the proper closing menu functionality will never fire and leave menu in bad state

**Comment by Patta** [comment] 2022-01-26 16:54
It could be solved by set the node-type of the page to your main page wrap/div in the off-canvas configurations. https://mmenujs.com/docs/core/off-canvas.html#h2

**Comment by jannakha** [comment] 2022-01-26 23:08
please elaborate?
MMenu automatically assigns ids to each element (mm-1, mm-2, ...)
My setup is as default as it can be.

in my specific case MMenu assigns id to page container and when `<a class="mm-wrapper__blocker mm-slideout" id="mm-0" title="Close menu" tabindex="-1" href="#mm-6"></a>` element is clicked to close menu `href=#mm-6` is checked against `#6` because it checks originalId vs href attribute:

https://github.com/FrDH/mmenu-js/blob/92fafdd60baf04c4507d121b5cc26b158e13e938/dist/core/offcanvas/mmenu.offcanvas.js#L78

**Comment by jannakha** [comment] 2022-01-26 23:12
it's a bug in v9.0

see v 8.5
https://github.com/FrDH/mmenu-js/blob/cc566754025757a4f7dcf00f4b807311c15eba5d/src/core/offcanvas/mmenu.offcanvas.ts#L153

to close menu: full page container id is compared with href, not `originalId`

**Comment by FrDH** [comment] 2022-01-27 08:38
This issue should be fixed in 9.0.3

**Comment by alextenczar** [comment] 2022-02-02 14:10
Still having this issue in 9.0.3. Anyone else?

**Comment by FrDH** [comment] 2022-02-06 20:41
Could you share an example of what isnt working? The demo's and other tests I dd seem to work as intended.

**Comment by alextenczar** [comment] 2022-02-16 21:39
@FrDH sorry for the late response.
Yeah, so basically on the newer verisons the menu doesn't take up the entire width of the page when it should.
9.0.4 menu (broken)
![broken](https://user-images.githubusercontent.com/24301038/154361609-b630e415-b9d0-44b4-a0f2-246fb0591b3a.png)
8.5.24 menu (working)
![working](https://user-images.githubusercontent.com/24301038/154361668-f1ae782f-0e05-4ca6-9961-52f5c3141c51.png)

**Comment by o15a3d4l11s2** [comment] 2022-03-18 11:20
@FrDH, what happened to the extensions? I cannot find any information about `fullscreen` or `mutiline` extension anywhere in the website anymore?

**Comment by FrDH** [comment] 2022-03-22 10:10
the extensions were moved or removed:

**fullscreen**: removed
Just set the `--mm-size`, `--mm-min-size` and `--mm-max-size` CSS variables to `100%`:
```
:root {
  --mm-size: 100%;
  --mm-min-size: 100%;
  --mm-max-size: 100%;
}
```

**positioning**: now part of the `offCanvas` add-on:
```
new Mmenu("#menu, {
   offCanvas: {
    position: "right"
  }
})
```

**theme**: now part of the core:
```
new Mmenu("#menu, {
   theme: "dark"
})
```

I think that were all.

**Closed** 2022-06-05 18:50 UTC
