### ISSUE TITLE
Hello, you have a bug with multiple clicks.

### ISSUE THREAD

**Issue by weldone-dev** [FrDH/mmenu-js#1115] opened 2020-02-25 13:20 UTC
![JMvRoHwnr8](https://user-images.githubusercontent.com/27072272/75250945-990dbe80-57ea-11ea-85f8-eeab90be53b3.gif)

**Comment by ROm0** [comment] 2020-02-25 13:31
If the bug does not play, click more often. 
How can I fix it?

**Comment by FrDH** [comment] 2020-02-27 11:15
This could be due to the exampe running in an iframe, it somehow behaves buggy. Have you tried opening it in a new browser tab (without the iframe)?

**Comment by ROm0** [comment] 2020-02-27 11:38
It is not related to iframe.
![13DZat0vMA](https://user-images.githubusercontent.com/27072272/75441507-d69b5480-596e-11ea-8ea0-b466b8055b72.gif)

https://mmenujs.com/demo/index.html?demo=home-blue

**Comment by ROm0** [comment] 2020-02-27 11:41
![DvGB2nfARW](https://user-images.githubusercontent.com/27072272/75441691-2a0da280-596f-11ea-8838-2f29d0abf5df.gif)

**Comment by ROm0** [comment] 2020-02-27 11:43
https://mmenujs.com/demo/index.html?demo=menu-advanced-4 
![ZrQ6HmWQSi](https://user-images.githubusercontent.com/27072272/75441842-6fca6b00-596f-11ea-9bd1-aaf7c2239791.gif)
And this example generally breaks the site

**Comment by ROm0** [comment] 2020-02-27 11:57
If you remove the mm-wrapper_opening class from the body with a bug, the menu is corrected
![ATtsY667mE](https://user-images.githubusercontent.com/27072272/75442904-6c37e380-5971-11ea-89e4-e60924228048.gif)

**Comment by FrDH** [comment] 2020-03-07 22:09
Thank you for the info, I was now able to reproduce the issue. I'll see if I can debug what is causing this.

**Comment by FrDH** [comment] 2020-10-20 19:38
Will probably be fixed in the next major release.

**Closed** 2020-11-08 22:17 UTC
Labels: bug

**Comment by weldone-dev** [comment] 2021-02-21 12:38
problem still exists
