### ISSUE TITLE
Conflict with modal scroll locking (e.g. fancybox and body-scroll-lock)

### ISSUE THREAD

**Issue by vaiil** [FrDH/mmenu-js#1049] opened 2019-08-26 19:58 UTC
Usually, modal windows block page scrolling via smth like that:
```
body {
overflow: hidden
}
```
But mmenu add `mm-wrapper` class to `html` (instead of `body`), that makes impossible to hide scrollbar using previous code.
I've solved it by changing `wrpr` element to `body` using hooks:
```
'initMenu:before': function () {
    this.node.wrpr = document.body
}
```
And it seems to be OK. So are there any reasons to use html as wrapper?

**Comment by vaiil** [comment] 2019-08-28 13:34
I've realised that I was wrong. It works OK in IOS Safari, but doesn't work properly in Chrome.

**Comment by FrDH** [comment] 2019-09-04 09:46
I'm going to close this issue as it is (sort of) a duplicate of the other one :)

**Closed by FrDH** 2019-09-04 09:46 UTC
