### ISSUE TITLE
Drag addon issue in 8.4

### ISSUE THREAD

**Issue by lcsikos** [FrDH/mmenu-js#1094] opened 2019-12-13 10:07 UTC
Hi Fred, 
I just tested the drag add on in V8.4 with these options:

drag : {	
open: true, 
node: document.body
}

If you start to touch and drag the menu from the left, the menu and the rest of the page move together at the beginning but after a while the menu releases from the rest of the page:
![image](https://user-images.githubusercontent.com/33608825/70791197-e86d5280-1d96-11ea-8003-898e86f28840.png)

After touchend the menu "jumps" to the right position. I tested it on Chrome V78.0.3904.108

**Comment by FrDH** [comment] 2019-12-21 13:32
Does it help if you do not set the `drag.node` option?

**Comment by lcsikos** [comment] 2019-12-22 21:03
Definitely not: if I do not set the drag.node option, the drag does not work.

**Comment by FrDH** [comment] 2019-12-24 09:33
Is there an online example I could have a look at?
I just tried without specifying a node at it worked as intended:
````js
new Mmenu("#my-menu", {
   drag: true
});
````

**Comment by lcsikos** [comment] 2019-12-24 15:14
Ok, I just tested one of your tutorials: https://mmenujs.com/demo/index.html?demo=columns
The only thing I changed in index.html, I inserted drag: true:

`new Mmenu("#menu", {
columns: true**,
drag: true**}, {});`

After that I tested it on desktop Chrome V79.0.3945.88, the drag worked without the issue mentioned above. But if you use Chrome DevTools and test it for devices (Ctrl+Shift+M in DevTools), the drag doesn't work (The first example I have attached also din't work on mobile devices but first I wanted to investigate the curious behavior in "desktop" view). The same behavior is if you test your tutorial with "drag: true" on real mobile devices, in my case: Samsung Galaxy S9 (Chrome V79.0.3945.93 or Samsung Browser V10.2.0053).

**Comment by FrDH** [comment] 2019-12-29 14:35
I think I found the issue, for mouse events it's `event.pageX`, for touch events it should be `event.touches[0].pageX`. I'll see if I can fix this shortly.

**Comment by FrDH** [comment] 2019-12-29 15:45
Try version 8.4.5,

Should be fixed :)

**Comment by lcsikos** [comment] 2020-01-01 14:09
It seems to be working now in 8.4.5. Thanks a lot for the quick issue fix.

**Closed** 2020-01-11 20:55 UTC
Labels: can't reproduce
