### ISSUE TITLE
Safari Mobile Browser - Stop the title bar (across the top) moving when the user swipes down

### ISSUE THREAD

**Issue by bluenose1970** [FrDH/mmenu-js#1020] opened 2019-05-31 15:04 UTC
I have a menu that partially collapses to just show icons down the left, when fully expanded it shows the icon & some text for each option.

When the menu is collapsed and the user swipes down it reveals the full menu witihn the scroll space. Is there any way to stop this so the title bar across the top doesn't move on swipe down?

**Comment by FrDH** [comment] 2019-05-31 18:50
Is there an online example I could have a look at?

**Comment by bluenose1970** [comment] 2019-06-07 16:13
A bit similar to this example.

http://mmenu.frebsite.nl/demo/index.html?demo=menu-onepage

Swiping down on a mobile device moves the title bar down, can this title bar remain at the top page even when the user has swiped down?

**Comment by FrDH** [comment] 2019-06-08 14:31
Ok, I see what you mean.
This behavior is what the [scroll bug fix](http://www.mmenujs.com/documentation/core/scroll-bug-fix.html) add-on intents to prevent. It is activated by default, so apparently it isn't working as intended.

I'll have a look at it later on.
Thank you for reporting the issue.

**Comment by FrDH** [comment] 2019-06-09 22:03
I made some changes in [the develop branche](https://github.com/FrDH/mmenu-js/tree/develop).
Tested it in Safari, Chrome and FF on an iPhone.
Please give it a try and let me know if it improved the behavior.

**Comment by bluenose1970** [comment] 2019-06-10 08:40
Thanks for the fix.

Seems to be ok now on Android (tested v7), but on Safari (iOS 12.3.1) the issues still remains unfortunately, the title bar still scrolls down on swipe down.

**Comment by FrDH** [comment] 2019-06-10 11:44
Are you sure? I developed and tested the fix using an iPhone 12.3.1 ... :/
Do you have an online example of the page that you're testing?

**Comment by bluenose1970** [comment] 2019-06-10 12:45
Unfortunately I don't have an online demo page.

I can replicate the issue with the demo project within the develop branch - the /demo/default.html page has the same behaviour where you can drag the title bar on swipe, tested on iPhone & iPad.

**Comment by FrDH** [comment] 2019-07-12 21:40
should be fixed in 8.2

**Closed** 2019-07-18 07:55 UTC
Labels: bug, next release
